services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: eduportal_db
      POSTGRES_USER: eduportal_user
      POSTGRES_PASSWORD: eduportal_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_NAME: eduportal_db
      DB_USER: eduportal_user
      DB_PASSWORD: eduportal_pass
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

volumes:
  postgres_data: